package com.triton.product.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Document(value = "product")
public class Product {

    @Id
    private String id;
    private String name;
    private String skuCode;
    private String description;
    private BigDecimal price;

//    GENERATED BY LOMBOK
//    public Product(String id, String name, String description, BigDecimal price) {
//        this.id = id;
//        this.name = name;
//        this.description = description;
//        this.price = price;
//    }
//
//    public Product() {
//    }


}
